#ifndef TASICMD_CONFIGURATION_H_
#define TASICMD_CONFIGURATION_H_

#ifndef TASICMD_MAX_LINE_LENGTH
#define TASICMD_MAX_LINE_LENGTH (128u)
#endif



#ifndef TCMD_USE_64BIT_PRECISION
#define TCMD_USE_64BIT_PRECISION (0u)
#endif

#endif // TASICMD_CONFIGURATION_H_
